#:schema node_modules/wrangler/config-schema.json
name = "cf-langgraph"
main = "index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-12-26"

assets = { directory = "public" }

[build]
command = "esbuild client.tsx --bundle --outdir=public/dist --format=esm --target=esnext"

# Workers Logs
[observability]
enabled = true

# [placement]
# mode = "smart"

# Best to name these the same thing so you don't get confused
[[durable_objects.bindings]]
# name of the binding in the worker
name = "Agent"
# name of your class
class_name = "Agent"

# Needed for the sqlite database in the DO
[[migrations]]
tag = "v1"
new_sqlite_classes = ["Agent"]
